apiVersion: v1
kind: Service
metadata:
    name: "clust-2ee5"
    labels:
        app: "clust-2ee5"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "clust-2ee5"