on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mycontainervivek.azurecr.io
        username: ${{secrets.acr_mycontainervivek_username}}
        password: ${{secrets.acr_mycontainervivek_password}}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t mycontainervivek.azurecr.io/clust2ee5:${{github.sha}}
        docker push mycontainervivek.azurecr.io/clust2ee5:${{github.sha}}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{secrets.aks_clust_kubeConfig}}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep clust2ee5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace clust2ee5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: clust2ee5
        container-registry-url: mycontainervivek.azurecr.io
        container-registry-username: ${{secrets.acr_mycontainervivek_username}}
        container-registry-password: ${{secrets.acr_mycontainervivek_password}}
        secret-name: clustdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: clust2ee5
        manifests: |
          ./manifests/deployment-2ee5.yml
          ./manifests/service-2ee5.yml
        images: |
          mycontainervivek.azurecr.io/clust2ee5:${{github.sha}}
        imagepullsecrets: |
          clustdockerauth